package ShareMarket;

/**
* ShareMarket/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Saturday, March 1, 2025 12:55:31 AM EST
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ShareMarket.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (ShareMarket.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ShareMarket.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ShareMarket.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ShareMarket.ServerHelper.type ();
  }

}
