package ShareMarket;


/**
* ShareMarket/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Saturday, March 1, 2025 12:55:31 AM EST
*/

public interface ServerOperations 
{

  // Admin Operations
  String addShare (String shareID, String shareType, int capacity);
  String removeShare (String shareID, String shareType);
  String listShareAvailability (String shareType);
  String purchaseRemoteShare (String buyerID, String shareID, String shareType, int shareCount, String targetMarket);
  String sellRemoteShare (String buyerID, String shareID, String shareType, int shareCount, String targetMarket);

  // Buyer Operations
  String purchaseShare (String buyerID, String shareID, String shareType, int shareCount);
  String getShares (String buyerID);
  String sellShare (String buyerID, String shareID, int shareCount);
  String swapShares (String buyerID, String oldShareID, String oldShareType, String newShareID, String newShareType);
} // interface ServerOperations
