package ShareMarket;


/**
* ShareMarket/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ShareMarket.idl
* Saturday, March 1, 2025 12:55:31 AM EST
*/

public interface Server extends ShareMarket.ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Server
